version: 16
jobs:
- name: Push to GitHub
  steps:
  - !PushRepository
    name: Push to Github
    remoteUrl: https://github.com/khose-ie/shadowsocks-docker-solution
    userName: khose-ie
    passwordSecret: github-token
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    projects: khose-ie/shadowsocks-docker-solution
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Pull from GitHub
  steps:
  - !PullRepository
    name: Pull from GitHub
    remoteUrl: https://github.com/khose-ie/shadowsocks-docker-solution
    userName: khose-ie
    passwordSecret: github-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 10 10 * ?
    projects: khose-ie/shadowsocks-docker-solution
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
