version: "3"
services:
    shadowsocks:
        image: hyklose/shadowsocks:latest
        container_name: shadowsocks-server
        restart: unless-stopped
        entrypoint: ssserver
        env_file:
            - config.env
        networks:
            - shadowsocks

    kcptun:
        image: hyklose/kcptun:latest
        container_name: shadowsocks-kcptun
        restart: unless-stopped
        entrypoint: kcpserver
        env_file:
            - config.env
        networks:
            - shadowsocks
        ports:
            - "4000:4000/udp"

networks:
    shadowsocks:
        name: shadowsocks
