name: "Login to DockerHub"

runs:
  using: "composite"

  steps:
  - name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ env.DOCKERHUB_USERNAME }}
      password: ${{ env.DOCKERHUB_TOKEN }}
