name: Release

on:
  push:
    branches: master

env:
  ARTIFACT: shadowsocks
  PHASE: release
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  determine-version:
    name: Determine version
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0
    outputs:
      version: ${{ env.VERSION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Generate version
      uses: ./.github/workflows/actions/determine-version/generate-version
    - name: Tag version in git
      uses: ./.github/workflows/actions/determine-version/tag-version

  publish-github:
    name: Publish GitHub artifacts
    runs-on: ubuntu-latest
    needs: determine-version
    env:
      RELEASE_URL: no_url
      VERSION: ${{ needs.determine-version.outputs.version }}

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Create GitHub release
      uses: ./.github/workflows/actions/publish-github/create-release
    - name: Upload release artifacts
      uses: ./.github/workflows/actions/publish-github/upload-artifact

  publish-dockerhub:
    name: Publish DockerHub image
    runs-on: ubuntu-latest
    needs: determine-version
    env:
      REPOSITORY: hyklose
      VERSION: ${{ needs.determine-version.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: ./.github/workflows/actions/publish-dockerhub/login
    - name: Upload kcptun image
      uses: ./.github/workflows/actions/publish-dockerhub/upload-kcptun
    - name: Upload privoxy image
      uses: ./.github/workflows/actions/publish-dockerhub/upload-privoxy
    - name: Upload shadowsocks image
      uses: ./.github/workflows/actions/publish-dockerhub/upload-shadowsocks
